name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        coq_version:
          - '8.15'
          - dev
        ocaml_version: ['4.14-flambda']
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - uses: coq-community/docker-coq-action@v1
        with:
          opam_file: 'coq-pact-model.opam'
          coq_version: ${{ matrix.coq_version }}
          ocaml_version: ${{ matrix.ocaml_version }}
  nix-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        coq_version:
          - '8.15'
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - uses: nixbuild/nix-quick-install-action@v14
      - run: nix-build -Q . -A pact-model_8_15.out
      - run: nix-build -Q . -A pact-model_8_15.env
      - run: nix-store -qR --include-outputs $(nix-instantiate shell.nix) | xargs nix-store --realise | xargs nix-store --query --requisites | AWS_ACCESS_KEY_ID="001d7f59d16a7a40000000007" AWS_SECRET_ACCESS_KEY="K001bnk1qAEnhBv7WX7NIQEutjqvFQc" xargs nix --extra-experimental-features nix-command copy --to "s3://jw-nix-cache?region=us-west-001&endpoint=s3.us-west-001.backblazeb2.com" --no-check-sigs
